server:
  port: 8188
  forward-headers-strategy: framework
spring:
  jackson:
    parser:
      strict-duplicate-detection: true
    serialization:
      indent-output: true
    deserialization:
      fail-on-reading-dup-tree-key: true
  application:
    name: product-service
  datasource:
    password: ''
    url: ''
    username: ''
  jpa:
    show-sql: true
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        jdbc:
          batch_size: 10
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        connection.provider_disables_autocommit: true
        format_sql: true
    open-in-view: false
  artemis:
    mode: native
    broker-url: ''
    user: ''
    password: ''
  servlet.multipart.max-file-size: 2MB
  main:
    allow-bean-definition-overriding: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  server:
    port: 8090

logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(%X{traceId}){blue} %clr( ){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'
  level:
    org:
      zalando:
        logbook: trace
      hibernate:
        SQL: ERROR
        type:
          descriptor:
            sql:
              BasicBinder: ERROR
kafka:
  bootstrapServer: ${HOST}:${KAFKA_PORT}
  groupId: ${GROUP_ID}
  replyMessageMaximumSize: 100000000
  maxRequestSize: 100000000
  maxPartitionFetchBytes: 100000000
  autoOffsetResetConfig: "earliest"
  requestTimeoutMs: 60000