name: Ci cd Dev environment

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-cd-dev-env:
    environment: Develop environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build and Unit Test
        if: success()
        run: mvn clean install -DskipTests

      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar

      - name: Log in to the Container registry
#        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push Docker image
#        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v3
        with:
          context: ./
          push: true
          tags: ghcr.io/ntgelite/product:latest
